name: cicd-feature

on:
  push:
    branches:
      - feature/*
      - issue/*
      - bugfix/*
      - hotfix/*
      - chore/*

jobs:
  package:
    name: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-22.04', 'windows-2022', 'macos-13']

    runs-on: ${{ matrix.os }}
    steps:
      # Checkout the code.
      - name: Checkout
        uses: actions/checkout@v4

      # Set environment variables
      - name: Set env variables
        shell: bash
        # We set env variables on the GITHUB_ENV variable so they value is available in all consecutive steps.
        run: |
          echo "PYTHON_VERSION=3.11.4" >> "$GITHUB_ENV"
          echo "NODE_VERSION=22.x" >> "$GITHUB_ENV"
          echo "GITHUB_TOKEN=${{ inputs.GITHUB_TOKEN }}" >> "$GITHUB_ENV"

      # Setup Node
      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@crossmodel'
          cache: 'yarn'

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Build dev package
        shell: bash
        run: |
          yarn --skip-integrity-check --network-timeout 100000
          yarn build:packages
          yarn theia:electron build:prod
          yarn theia:electron package:prod
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Upload ${{ runner.os }} installer
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-installer
          path: |
            applications/electron-app/dist/CrossModel *.*
          retention-days: 1
